name: OFP Decrypter by Area69Labs

on:
  workflow_dispatch:
    inputs:
      ofp_link:
        description: 'OFP Firmaware Link'
        required: true

env:
  OFP_LINK: ${{ github.event.inputs.ofp_link }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Download OFP Firmware
        run: |
          aria2c -c -s16 -x16 "$OFP_LINK" 2>/dev/null || wget -q --show-progress "$OFP_LINK"
          OFPFILE=${OFP_LINK##*/}
          echo "OFP_FILE=${OFPFILE}" >> ${GITHUB_ENV}
          OFPNAME=${OFPFILE%.*}
          echo "OFP_NAME=${OFPNAME}" >> ${GITHUB_ENV}

      - name: Prepare Decrypter and Decrypt OFP
        run: |
          sudo apt-fast update -qqy
          sudo apt-fast install -qqy openssl rsync sshpass
          sudo pip3 install --upgrade pip wheel setuptools
          sudo pip3 install --upgrade pycryptodome
          sudo apt install simg2img
          git clone https://github.com/bkerler/oppo_decrypt.git --depth=1
          printf "Trying to Decrypt QC OFP...\n"
          python3 ./oppo_decrypt/ofp_mtk_decrypt.py "$OFP_FILE" out 2>/dev/null
          mkdir super
          mv out/*super*.img super/
          cd super
          simg2img *super*.img super.img
          mv super.img ../out         
          cd ..

      - name: Compress Decrypted Zip
        run: |
          pwd
          zip -r9 Decrypted."${OFPFILE}".zip out/
          zip -r superimages.zip super/
    
      - name: Upload Decrypted Zip
        run: |
          pwd
          ls
          wget https://sauraj.rommirrorer.workers.dev/0:/rclonesetup.sh
          bash rclonesetup.sh
          rclone -P copy Decrypted_"${OFPFILE}".zip rom:/decrypted_ofp/"${OFPFILE}"_decrypt
          rclone -P copy superimages.zip rom:/decrypted_ofp/"${OFPFILE}"_decrypt

      - name: Upload Decrypted Zip
        run: |
          echo '''zip LINK: https://sauraj.rommirrorer.workers.dev/0:/decrypted_ofp/"${OFPFILE}"_decrypt'''
          echo "Edited By Sauraj"
          
          
